/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef REMOTE_MEM_TEST_TYPES_H
#define REMOTE_MEM_TEST_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* other thrift includes */
#include "shared_types.h"

/* custom thrift includes */

/* begin types */

/* constants */

/* struct RemoteMemTestPingArgs */
struct _RemoteMemTestPingArgs
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _RemoteMemTestPingArgs RemoteMemTestPingArgs;

struct _RemoteMemTestPingArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestPingArgsClass RemoteMemTestPingArgsClass;

GType remote_mem_test_ping_args_get_type (void);
#define TYPE_REMOTE_MEM_TEST_PING_ARGS (remote_mem_test_ping_args_get_type())
#define REMOTE_MEM_TEST_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_PING_ARGS, RemoteMemTestPingArgs))
#define REMOTE_MEM_TEST_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_PING_ARGS, RemoteMemTestPingArgsClass))
#define IS_REMOTE_MEM_TEST_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_PING_ARGS))
#define IS_REMOTE_MEM_TEST_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_PING_ARGS))
#define REMOTE_MEM_TEST_PING_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_PING_ARGS, RemoteMemTestPingArgsClass))

/* struct RemoteMemTestPingResult */
struct _RemoteMemTestPingResult
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _RemoteMemTestPingResult RemoteMemTestPingResult;

struct _RemoteMemTestPingResultClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestPingResultClass RemoteMemTestPingResultClass;

GType remote_mem_test_ping_result_get_type (void);
#define TYPE_REMOTE_MEM_TEST_PING_RESULT (remote_mem_test_ping_result_get_type())
#define REMOTE_MEM_TEST_PING_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_PING_RESULT, RemoteMemTestPingResult))
#define REMOTE_MEM_TEST_PING_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_PING_RESULT, RemoteMemTestPingResultClass))
#define IS_REMOTE_MEM_TEST_PING_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_PING_RESULT))
#define IS_REMOTE_MEM_TEST_PING_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_PING_RESULT))
#define REMOTE_MEM_TEST_PING_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_PING_RESULT, RemoteMemTestPingResultClass))

/* struct RemoteMemTestAllocateMemArgs */
struct _RemoteMemTestAllocateMemArgs
{ 
  ThriftStruct parent; 

  /* public */
  gint32 size;
  gboolean __isset_size;
};
typedef struct _RemoteMemTestAllocateMemArgs RemoteMemTestAllocateMemArgs;

struct _RemoteMemTestAllocateMemArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestAllocateMemArgsClass RemoteMemTestAllocateMemArgsClass;

GType remote_mem_test_allocate_mem_args_get_type (void);
#define TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS (remote_mem_test_allocate_mem_args_get_type())
#define REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS, RemoteMemTestAllocateMemArgs))
#define REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS, RemoteMemTestAllocateMemArgsClass))
#define IS_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS))
#define IS_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS))
#define REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS, RemoteMemTestAllocateMemArgsClass))

/* struct RemoteMemTestAllocateMemResult */
struct _RemoteMemTestAllocateMemResult
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * success;
  gboolean __isset_success;
  CallException * ouch;
  gboolean __isset_ouch;
};
typedef struct _RemoteMemTestAllocateMemResult RemoteMemTestAllocateMemResult;

struct _RemoteMemTestAllocateMemResultClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestAllocateMemResultClass RemoteMemTestAllocateMemResultClass;

GType remote_mem_test_allocate_mem_result_get_type (void);
#define TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT (remote_mem_test_allocate_mem_result_get_type())
#define REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT, RemoteMemTestAllocateMemResult))
#define REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT, RemoteMemTestAllocateMemResultClass))
#define IS_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT))
#define IS_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT))
#define REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT, RemoteMemTestAllocateMemResultClass))

/* struct RemoteMemTestReadMemArgs */
struct _RemoteMemTestReadMemArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * pointer;
  gboolean __isset_pointer;
};
typedef struct _RemoteMemTestReadMemArgs RemoteMemTestReadMemArgs;

struct _RemoteMemTestReadMemArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestReadMemArgsClass RemoteMemTestReadMemArgsClass;

GType remote_mem_test_read_mem_args_get_type (void);
#define TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS (remote_mem_test_read_mem_args_get_type())
#define REMOTE_MEM_TEST_READ_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS, RemoteMemTestReadMemArgs))
#define REMOTE_MEM_TEST_READ_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS, RemoteMemTestReadMemArgsClass))
#define IS_REMOTE_MEM_TEST_READ_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS))
#define IS_REMOTE_MEM_TEST_READ_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS))
#define REMOTE_MEM_TEST_READ_MEM_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS, RemoteMemTestReadMemArgsClass))

/* struct RemoteMemTestReadMemResult */
struct _RemoteMemTestReadMemResult
{ 
  ThriftStruct parent; 

  /* public */
  CallException * ouch;
  gboolean __isset_ouch;
};
typedef struct _RemoteMemTestReadMemResult RemoteMemTestReadMemResult;

struct _RemoteMemTestReadMemResultClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestReadMemResultClass RemoteMemTestReadMemResultClass;

GType remote_mem_test_read_mem_result_get_type (void);
#define TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT (remote_mem_test_read_mem_result_get_type())
#define REMOTE_MEM_TEST_READ_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT, RemoteMemTestReadMemResult))
#define REMOTE_MEM_TEST_READ_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT, RemoteMemTestReadMemResultClass))
#define IS_REMOTE_MEM_TEST_READ_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT))
#define IS_REMOTE_MEM_TEST_READ_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT))
#define REMOTE_MEM_TEST_READ_MEM_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT, RemoteMemTestReadMemResultClass))

/* struct RemoteMemTestWriteMemArgs */
struct _RemoteMemTestWriteMemArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * pointer;
  gboolean __isset_pointer;
  gchar * message;
  gboolean __isset_message;
};
typedef struct _RemoteMemTestWriteMemArgs RemoteMemTestWriteMemArgs;

struct _RemoteMemTestWriteMemArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestWriteMemArgsClass RemoteMemTestWriteMemArgsClass;

GType remote_mem_test_write_mem_args_get_type (void);
#define TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS (remote_mem_test_write_mem_args_get_type())
#define REMOTE_MEM_TEST_WRITE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS, RemoteMemTestWriteMemArgs))
#define REMOTE_MEM_TEST_WRITE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS, RemoteMemTestWriteMemArgsClass))
#define IS_REMOTE_MEM_TEST_WRITE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS))
#define IS_REMOTE_MEM_TEST_WRITE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS))
#define REMOTE_MEM_TEST_WRITE_MEM_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS, RemoteMemTestWriteMemArgsClass))

/* struct RemoteMemTestWriteMemResult */
struct _RemoteMemTestWriteMemResult
{ 
  ThriftStruct parent; 

  /* public */
  CallException * ouch;
  gboolean __isset_ouch;
};
typedef struct _RemoteMemTestWriteMemResult RemoteMemTestWriteMemResult;

struct _RemoteMemTestWriteMemResultClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestWriteMemResultClass RemoteMemTestWriteMemResultClass;

GType remote_mem_test_write_mem_result_get_type (void);
#define TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT (remote_mem_test_write_mem_result_get_type())
#define REMOTE_MEM_TEST_WRITE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT, RemoteMemTestWriteMemResult))
#define REMOTE_MEM_TEST_WRITE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT, RemoteMemTestWriteMemResultClass))
#define IS_REMOTE_MEM_TEST_WRITE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT))
#define IS_REMOTE_MEM_TEST_WRITE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT))
#define REMOTE_MEM_TEST_WRITE_MEM_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT, RemoteMemTestWriteMemResultClass))

/* struct RemoteMemTestFreeMemArgs */
struct _RemoteMemTestFreeMemArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * pointer;
  gboolean __isset_pointer;
};
typedef struct _RemoteMemTestFreeMemArgs RemoteMemTestFreeMemArgs;

struct _RemoteMemTestFreeMemArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestFreeMemArgsClass RemoteMemTestFreeMemArgsClass;

GType remote_mem_test_free_mem_args_get_type (void);
#define TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS (remote_mem_test_free_mem_args_get_type())
#define REMOTE_MEM_TEST_FREE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS, RemoteMemTestFreeMemArgs))
#define REMOTE_MEM_TEST_FREE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS, RemoteMemTestFreeMemArgsClass))
#define IS_REMOTE_MEM_TEST_FREE_MEM_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS))
#define IS_REMOTE_MEM_TEST_FREE_MEM_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS))
#define REMOTE_MEM_TEST_FREE_MEM_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS, RemoteMemTestFreeMemArgsClass))

/* struct RemoteMemTestFreeMemResult */
struct _RemoteMemTestFreeMemResult
{ 
  ThriftStruct parent; 

  /* public */
  CallException * ouch;
  gboolean __isset_ouch;
};
typedef struct _RemoteMemTestFreeMemResult RemoteMemTestFreeMemResult;

struct _RemoteMemTestFreeMemResultClass
{
  ThriftStructClass parent;
};
typedef struct _RemoteMemTestFreeMemResultClass RemoteMemTestFreeMemResultClass;

GType remote_mem_test_free_mem_result_get_type (void);
#define TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT (remote_mem_test_free_mem_result_get_type())
#define REMOTE_MEM_TEST_FREE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT, RemoteMemTestFreeMemResult))
#define REMOTE_MEM_TEST_FREE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT, RemoteMemTestFreeMemResultClass))
#define IS_REMOTE_MEM_TEST_FREE_MEM_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT))
#define IS_REMOTE_MEM_TEST_FREE_MEM_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT))
#define REMOTE_MEM_TEST_FREE_MEM_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT, RemoteMemTestFreeMemResultClass))

#endif /* REMOTE_MEM_TEST_TYPES_H */
