/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "remote_mem_test.h"

gboolean
remote_mem_test_if_ping (RemoteMemTestIf *iface, GError **error)
{
  return REMOTE_MEM_TEST_IF_GET_INTERFACE (iface)->ping (iface, error);
}

gboolean
remote_mem_test_if_allocate_mem (RemoteMemTestIf *iface, GByteArray ** _return, const gint32 size, CallException ** ouch, GError **error)
{
  return REMOTE_MEM_TEST_IF_GET_INTERFACE (iface)->allocate_mem (iface, _return, size, ouch, error);
}

gboolean
remote_mem_test_if_read_mem (RemoteMemTestIf *iface, const GByteArray * pointer, CallException ** ouch, GError **error)
{
  return REMOTE_MEM_TEST_IF_GET_INTERFACE (iface)->read_mem (iface, pointer, ouch, error);
}

gboolean
remote_mem_test_if_write_mem (RemoteMemTestIf *iface, const GByteArray * pointer, const gchar * message, CallException ** ouch, GError **error)
{
  return REMOTE_MEM_TEST_IF_GET_INTERFACE (iface)->write_mem (iface, pointer, message, ouch, error);
}

gboolean
remote_mem_test_if_free_mem (RemoteMemTestIf *iface, const GByteArray * pointer, CallException ** ouch, GError **error)
{
  return REMOTE_MEM_TEST_IF_GET_INTERFACE (iface)->free_mem (iface, pointer, ouch, error);
}

GType
remote_mem_test_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (RemoteMemTestIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "RemoteMemTestIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
remote_mem_test_if_interface_init (RemoteMemTestIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (RemoteMemTestClient, remote_mem_test_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_REMOTE_MEM_TEST_IF,
                                                remote_mem_test_if_interface_init));

enum _RemoteMemTestClientProperties
{
  PROP_0,
  PROP_REMOTE_MEM_TEST_CLIENT_INPUT_PROTOCOL,
  PROP_REMOTE_MEM_TEST_CLIENT_OUTPUT_PROTOCOL
};

void
remote_mem_test_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  RemoteMemTestClient *client = REMOTE_MEM_TEST_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_REMOTE_MEM_TEST_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_REMOTE_MEM_TEST_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
remote_mem_test_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  RemoteMemTestClient *client = REMOTE_MEM_TEST_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_REMOTE_MEM_TEST_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_REMOTE_MEM_TEST_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean remote_mem_test_client_send_ping (RemoteMemTestIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "ping", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "ping_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_recv_ping (RemoteMemTestIf * iface, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "ping", 4) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected ping", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_ping (RemoteMemTestIf * iface, GError ** error)
{
  if (!remote_mem_test_client_send_ping (iface, error))
    return FALSE;
  if (!remote_mem_test_client_recv_ping (iface, error))
    return FALSE;
  return TRUE;
}

gboolean remote_mem_test_client_send_allocate_mem (RemoteMemTestIf * iface, const gint32 size, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "allocate_mem", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "allocate_mem_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "size", T_I32, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, size, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_recv_allocate_mem (RemoteMemTestIf * iface, GByteArray ** _return, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "allocate_mem", 12) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected allocate_mem", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean remote_mem_test_client_allocate_mem (RemoteMemTestIf * iface, GByteArray ** _return, const gint32 size, CallException ** ouch, GError ** error)
{
  if (!remote_mem_test_client_send_allocate_mem (iface, size, error))
    return FALSE;
  if (!remote_mem_test_client_recv_allocate_mem (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean remote_mem_test_client_send_read_mem (RemoteMemTestIf * iface, const GByteArray * pointer, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "read_mem", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "read_mem_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pointer", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) pointer)->data, ((GByteArray *) pointer)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_recv_read_mem (RemoteMemTestIf * iface, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "read_mem", 8) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected read_mem", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean remote_mem_test_client_read_mem (RemoteMemTestIf * iface, const GByteArray * pointer, CallException ** ouch, GError ** error)
{
  if (!remote_mem_test_client_send_read_mem (iface, pointer, error))
    return FALSE;
  if (!remote_mem_test_client_recv_read_mem (iface, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean remote_mem_test_client_send_write_mem (RemoteMemTestIf * iface, const GByteArray * pointer, const gchar * message, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "write_mem", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "write_mem_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pointer", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) pointer)->data, ((GByteArray *) pointer)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "message", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, message, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_recv_write_mem (RemoteMemTestIf * iface, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "write_mem", 9) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected write_mem", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean remote_mem_test_client_write_mem (RemoteMemTestIf * iface, const GByteArray * pointer, const gchar * message, CallException ** ouch, GError ** error)
{
  if (!remote_mem_test_client_send_write_mem (iface, pointer, message, error))
    return FALSE;
  if (!remote_mem_test_client_recv_write_mem (iface, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean remote_mem_test_client_send_free_mem (RemoteMemTestIf * iface, const GByteArray * pointer, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "free_mem", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "free_mem_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pointer", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) pointer)->data, ((GByteArray *) pointer)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean remote_mem_test_client_recv_free_mem (RemoteMemTestIf * iface, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = REMOTE_MEM_TEST_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "free_mem", 8) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected free_mem", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean remote_mem_test_client_free_mem (RemoteMemTestIf * iface, const GByteArray * pointer, CallException ** ouch, GError ** error)
{
  if (!remote_mem_test_client_send_free_mem (iface, pointer, error))
    return FALSE;
  if (!remote_mem_test_client_recv_free_mem (iface, ouch, error))
    return FALSE;
  return TRUE;
}

static void
remote_mem_test_if_interface_init (RemoteMemTestIfInterface *iface)
{
  iface->ping = remote_mem_test_client_ping;
  iface->allocate_mem = remote_mem_test_client_allocate_mem;
  iface->read_mem = remote_mem_test_client_read_mem;
  iface->write_mem = remote_mem_test_client_write_mem;
  iface->free_mem = remote_mem_test_client_free_mem;
}

static void
remote_mem_test_client_init (RemoteMemTestClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
remote_mem_test_client_class_init (RemoteMemTestClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = remote_mem_test_client_set_property;
  gobject_class->get_property = remote_mem_test_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_REMOTE_MEM_TEST_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_REMOTE_MEM_TEST_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
remote_mem_test_handler_remote_mem_test_if_interface_init (RemoteMemTestIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (RemoteMemTestHandler, 
                         remote_mem_test_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_REMOTE_MEM_TEST_IF,
                                                remote_mem_test_handler_remote_mem_test_if_interface_init));

gboolean remote_mem_test_handler_ping (RemoteMemTestIf * iface, GError ** error)
{
  g_return_if_fail (IS_REMOTE_MEM_TEST_HANDLER (iface));

  REMOTE_MEM_TEST_HANDLER_GET_CLASS (iface)->ping (iface, error);
}

gboolean remote_mem_test_handler_allocate_mem (RemoteMemTestIf * iface, GByteArray ** _return, const gint32 size, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_REMOTE_MEM_TEST_HANDLER (iface));

  REMOTE_MEM_TEST_HANDLER_GET_CLASS (iface)->allocate_mem (iface, _return, size, ouch, error);
}

gboolean remote_mem_test_handler_read_mem (RemoteMemTestIf * iface, const GByteArray * pointer, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_REMOTE_MEM_TEST_HANDLER (iface));

  REMOTE_MEM_TEST_HANDLER_GET_CLASS (iface)->read_mem (iface, pointer, ouch, error);
}

gboolean remote_mem_test_handler_write_mem (RemoteMemTestIf * iface, const GByteArray * pointer, const gchar * message, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_REMOTE_MEM_TEST_HANDLER (iface));

  REMOTE_MEM_TEST_HANDLER_GET_CLASS (iface)->write_mem (iface, pointer, message, ouch, error);
}

gboolean remote_mem_test_handler_free_mem (RemoteMemTestIf * iface, const GByteArray * pointer, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_REMOTE_MEM_TEST_HANDLER (iface));

  REMOTE_MEM_TEST_HANDLER_GET_CLASS (iface)->free_mem (iface, pointer, ouch, error);
}

static void
remote_mem_test_handler_remote_mem_test_if_interface_init (RemoteMemTestIfInterface *iface)
{
  iface->ping = remote_mem_test_handler_ping;
  iface->allocate_mem = remote_mem_test_handler_allocate_mem;
  iface->read_mem = remote_mem_test_handler_read_mem;
  iface->write_mem = remote_mem_test_handler_write_mem;
  iface->free_mem = remote_mem_test_handler_free_mem;
}

static void
remote_mem_test_handler_init (RemoteMemTestHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
remote_mem_test_handler_class_init (RemoteMemTestHandlerClass *cls)
{
  cls->ping = NULL;
  cls->allocate_mem = NULL;
  cls->read_mem = NULL;
  cls->write_mem = NULL;
  cls->free_mem = NULL;
}

enum _RemoteMemTestProcessorProperties
{
  PROP_REMOTE_MEM_TEST_PROCESSOR_0,
  PROP_REMOTE_MEM_TEST_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (RemoteMemTestProcessor,
               remote_mem_test_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR);

typedef gboolean (* RemoteMemTestProcessorProcessFunction) (RemoteMemTestProcessor *, 
                                                            gint32,
                                                            ThriftProtocol *,
                                                            ThriftProtocol *,
                                                            GError **);

static gboolean
remote_mem_test_processor_process_ping (RemoteMemTestProcessor *self,
                                        gint32 sequence_id,
                                        ThriftProtocol *input_protocol,
                                        ThriftProtocol *output_protocol,
                                        GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  RemoteMemTestPingArgs * args =
    g_object_new (TYPE_REMOTE_MEM_TEST_PING_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    RemoteMemTestPingResult * result_struct;

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_REMOTE_MEM_TEST_PING_RESULT, NULL);

    if (remote_mem_test_handler_ping (REMOTE_MEM_TEST_IF (self->handler),
                                      error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "ping",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("RemoteMemTest.ping implementation returned FALSE "
                   "but did not set an error");

      ThriftApplicationException *xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "ping",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
remote_mem_test_processor_process_allocate_mem (RemoteMemTestProcessor *self,
                                                gint32 sequence_id,
                                                ThriftProtocol *input_protocol,
                                                ThriftProtocol *output_protocol,
                                                GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  RemoteMemTestAllocateMemArgs * args =
    g_object_new (TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint size;
    CallException * ouch = NULL;
    GByteArray * return_value;
    RemoteMemTestAllocateMemResult * result_struct;

    g_object_get (args,
                  "size", &size,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_REMOTE_MEM_TEST_ALLOCATE_MEM_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (remote_mem_test_handler_allocate_mem (REMOTE_MEM_TEST_IF (self->handler),
                                              &return_value,
                                              size,
                                              &ouch,
                                              error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "allocate_mem",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "allocate_mem",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("RemoteMemTest.allocate_mem implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "allocate_mem",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
remote_mem_test_processor_process_read_mem (RemoteMemTestProcessor *self,
                                            gint32 sequence_id,
                                            ThriftProtocol *input_protocol,
                                            ThriftProtocol *output_protocol,
                                            GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  RemoteMemTestReadMemArgs * args =
    g_object_new (TYPE_REMOTE_MEM_TEST_READ_MEM_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pointer;
    CallException * ouch = NULL;
    RemoteMemTestReadMemResult * result_struct;

    g_object_get (args,
                  "pointer", &pointer,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_REMOTE_MEM_TEST_READ_MEM_RESULT, NULL);

    if (remote_mem_test_handler_read_mem (REMOTE_MEM_TEST_IF (self->handler),
                                          pointer,
                                          &ouch,
                                          error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "read_mem",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "read_mem",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("RemoteMemTest.read_mem implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "read_mem",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (pointer != NULL)
      g_byte_array_unref (pointer);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
remote_mem_test_processor_process_write_mem (RemoteMemTestProcessor *self,
                                             gint32 sequence_id,
                                             ThriftProtocol *input_protocol,
                                             ThriftProtocol *output_protocol,
                                             GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  RemoteMemTestWriteMemArgs * args =
    g_object_new (TYPE_REMOTE_MEM_TEST_WRITE_MEM_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pointer;
    gchar * message;
    CallException * ouch = NULL;
    RemoteMemTestWriteMemResult * result_struct;

    g_object_get (args,
                  "pointer", &pointer,
                  "message", &message,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_REMOTE_MEM_TEST_WRITE_MEM_RESULT, NULL);

    if (remote_mem_test_handler_write_mem (REMOTE_MEM_TEST_IF (self->handler),
                                           pointer,
                                           message,
                                           &ouch,
                                           error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "write_mem",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "write_mem",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("RemoteMemTest.write_mem implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "write_mem",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (pointer != NULL)
      g_byte_array_unref (pointer);
    if (message != NULL)
      g_free (message);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
remote_mem_test_processor_process_free_mem (RemoteMemTestProcessor *self,
                                            gint32 sequence_id,
                                            ThriftProtocol *input_protocol,
                                            ThriftProtocol *output_protocol,
                                            GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  RemoteMemTestFreeMemArgs * args =
    g_object_new (TYPE_REMOTE_MEM_TEST_FREE_MEM_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pointer;
    CallException * ouch = NULL;
    RemoteMemTestFreeMemResult * result_struct;

    g_object_get (args,
                  "pointer", &pointer,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_REMOTE_MEM_TEST_FREE_MEM_RESULT, NULL);

    if (remote_mem_test_handler_free_mem (REMOTE_MEM_TEST_IF (self->handler),
                                          pointer,
                                          &ouch,
                                          error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "free_mem",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "free_mem",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("RemoteMemTest.free_mem implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "free_mem",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (pointer != NULL)
      g_byte_array_unref (pointer);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
remote_mem_test_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                         ThriftProtocol *input_protocol,
                                         ThriftProtocol *output_protocol,
                                         gchar *method_name,
                                         gint32 sequence_id,
                                         GError **error)
{
  RemoteMemTestProcessorProcessFunction process_function; 
  gboolean dispatch_result = FALSE;

  RemoteMemTestProcessor *self = REMOTE_MEM_TEST_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (REMOTE_MEM_TEST_PROCESSOR_GET_CLASS (self));

  process_function = g_hash_table_lookup (self->process_map, method_name);
  if (process_function != NULL)
  {
    dispatch_result = (*process_function) (self,
                                           sequence_id,
                                           input_protocol,
                                           output_protocol,
                                           error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
remote_mem_test_processor_set_property (GObject *object,
                                        guint property_id,
                                        const GValue *value,
                                        GParamSpec *pspec)
{
  RemoteMemTestProcessor *self = REMOTE_MEM_TEST_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_REMOTE_MEM_TEST_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
remote_mem_test_processor_get_property (GObject *object,
                                        guint property_id,
                                        GValue *value,
                                        GParamSpec *pspec)
{
  RemoteMemTestProcessor *self = REMOTE_MEM_TEST_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_REMOTE_MEM_TEST_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
remote_mem_test_processor_dispose (GObject *gobject)
{
  RemoteMemTestProcessor *self = REMOTE_MEM_TEST_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (remote_mem_test_processor_parent_class)->dispose (gobject);
}

static void
remote_mem_test_processor_finalize (GObject *gobject)
{
  RemoteMemTestProcessor *self = REMOTE_MEM_TEST_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (remote_mem_test_processor_parent_class)->finalize (gobject);
}

static void
remote_mem_test_processor_init (RemoteMemTestProcessor *self)
{
  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  g_hash_table_insert (self->process_map,
                       "ping", 
                       remote_mem_test_processor_process_ping);
  g_hash_table_insert (self->process_map,
                       "allocate_mem", 
                       remote_mem_test_processor_process_allocate_mem);
  g_hash_table_insert (self->process_map,
                       "read_mem", 
                       remote_mem_test_processor_process_read_mem);
  g_hash_table_insert (self->process_map,
                       "write_mem", 
                       remote_mem_test_processor_process_write_mem);
  g_hash_table_insert (self->process_map,
                       "free_mem", 
                       remote_mem_test_processor_process_free_mem);
}

static void
remote_mem_test_processor_class_init (RemoteMemTestProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = remote_mem_test_processor_dispose;
  gobject_class->finalize = remote_mem_test_processor_finalize;
  gobject_class->set_property = remote_mem_test_processor_set_property;
  gobject_class->get_property = remote_mem_test_processor_get_property;

  dispatch_processor_class->dispatch_call = remote_mem_test_processor_dispatch_call;
  cls->dispatch_call = remote_mem_test_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_REMOTE_MEM_TEST_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_REMOTE_MEM_TEST_PROCESSOR_HANDLER,
                                   param_spec);
}
