/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "simple_arr_comp.h"

gboolean
simple_arr_comp_if_increment_array (SimpleArrCompIf *iface, GByteArray ** _return, const GByteArray * arr, const gint8 value, const gint32 length, CallException ** ouch, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->increment_array (iface, _return, arr, value, length, ouch, error);
}

gboolean
simple_arr_comp_if_add_arrays (SimpleArrCompIf *iface, GByteArray ** _return, const GByteArray * array1, const GByteArray * array2, const gint32 length, CallException ** ouch, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->add_arrays (iface, _return, array1, array2, length, ouch, error);
}

gboolean
simple_arr_comp_if_mat_multiply (SimpleArrCompIf *iface, const GByteArray * array, const GByteArray * matrix, const gint32 length, const tuple * dimension, const GByteArray * result_ptr, CallException ** ouch, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->mat_multiply (iface, array, matrix, length, dimension, result_ptr, ouch, error);
}

gboolean
simple_arr_comp_if_word_count (SimpleArrCompIf *iface, gint32* _return, const GByteArray * story, const gint32 length, CallException ** ouch, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->word_count (iface, _return, story, length, ouch, error);
}

gboolean
simple_arr_comp_if_sort_array (SimpleArrCompIf *iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, CallException ** ouch, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->sort_array (iface, _return, num_array, length, ouch, error);
}

gboolean
simple_arr_comp_if_no_op (SimpleArrCompIf *iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, GError **error)
{
  return SIMPLE_ARR_COMP_IF_GET_INTERFACE (iface)->no_op (iface, _return, num_array, length, error);
}

GType
simple_arr_comp_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (SimpleArrCompIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "SimpleArrCompIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
simple_arr_comp_if_interface_init (SimpleArrCompIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (SimpleArrCompClient, simple_arr_comp_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_SIMPLE_ARR_COMP_IF,
                                                simple_arr_comp_if_interface_init));

enum _SimpleArrCompClientProperties
{
  PROP_0,
  PROP_SIMPLE_ARR_COMP_CLIENT_INPUT_PROTOCOL,
  PROP_SIMPLE_ARR_COMP_CLIENT_OUTPUT_PROTOCOL
};

void
simple_arr_comp_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  SimpleArrCompClient *client = SIMPLE_ARR_COMP_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SIMPLE_ARR_COMP_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_SIMPLE_ARR_COMP_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
simple_arr_comp_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  SimpleArrCompClient *client = SIMPLE_ARR_COMP_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SIMPLE_ARR_COMP_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_SIMPLE_ARR_COMP_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean simple_arr_comp_client_send_increment_array (SimpleArrCompIf * iface, const GByteArray * arr, const gint8 value, const gint32 length, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "increment_array", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "increment_array_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "arr", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) arr)->data, ((GByteArray *) arr)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "value", T_BYTE, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_byte (protocol, value, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_increment_array (SimpleArrCompIf * iface, GByteArray ** _return, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "increment_array", 15) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected increment_array", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean simple_arr_comp_client_increment_array (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * arr, const gint8 value, const gint32 length, CallException ** ouch, GError ** error)
{
  if (!simple_arr_comp_client_send_increment_array (iface, arr, value, length, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_increment_array (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean simple_arr_comp_client_send_add_arrays (SimpleArrCompIf * iface, const GByteArray * array1, const GByteArray * array2, const gint32 length, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "add_arrays", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "add_arrays_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "array1", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) array1)->data, ((GByteArray *) array1)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "array2", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) array2)->data, ((GByteArray *) array2)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_add_arrays (SimpleArrCompIf * iface, GByteArray ** _return, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "add_arrays", 10) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected add_arrays", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean simple_arr_comp_client_add_arrays (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * array1, const GByteArray * array2, const gint32 length, CallException ** ouch, GError ** error)
{
  if (!simple_arr_comp_client_send_add_arrays (iface, array1, array2, length, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_add_arrays (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean simple_arr_comp_client_send_mat_multiply (SimpleArrCompIf * iface, const GByteArray * array, const GByteArray * matrix, const gint32 length, const tuple * dimension, const GByteArray * result_ptr, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "mat_multiply", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "mat_multiply_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "array", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) array)->data, ((GByteArray *) array)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "matrix", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) matrix)->data, ((GByteArray *) matrix)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "dimension", T_STRUCT, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (dimension), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "result_ptr", T_STRING, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) result_ptr)->data, ((GByteArray *) result_ptr)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_mat_multiply (SimpleArrCompIf * iface, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "mat_multiply", 12) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected mat_multiply", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean simple_arr_comp_client_mat_multiply (SimpleArrCompIf * iface, const GByteArray * array, const GByteArray * matrix, const gint32 length, const tuple * dimension, const GByteArray * result_ptr, CallException ** ouch, GError ** error)
{
  if (!simple_arr_comp_client_send_mat_multiply (iface, array, matrix, length, dimension, result_ptr, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_mat_multiply (iface, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean simple_arr_comp_client_send_word_count (SimpleArrCompIf * iface, const GByteArray * story, const gint32 length, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "word_count", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "word_count_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "story", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) story)->data, ((GByteArray *) story)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_word_count (SimpleArrCompIf * iface, gint32* _return, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "word_count", 10) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected word_count", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_I32)
          {
            if ((ret = thrift_protocol_read_i32 (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean simple_arr_comp_client_word_count (SimpleArrCompIf * iface, gint32* _return, const GByteArray * story, const gint32 length, CallException ** ouch, GError ** error)
{
  if (!simple_arr_comp_client_send_word_count (iface, story, length, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_word_count (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean simple_arr_comp_client_send_sort_array (SimpleArrCompIf * iface, const GByteArray * num_array, const gint32 length, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "sort_array", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "sort_array_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "num_array", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) num_array)->data, ((GByteArray *) num_array)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_sort_array (SimpleArrCompIf * iface, GByteArray ** _return, CallException ** ouch, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "sort_array", 10) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected sort_array", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (TYPE_CALL_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, CALL_EXCEPTION_ERROR, CALL_EXCEPTION_ERROR_CODE, "CallException");
      return FALSE;
  }
  return TRUE;
}

gboolean simple_arr_comp_client_sort_array (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, CallException ** ouch, GError ** error)
{
  if (!simple_arr_comp_client_send_sort_array (iface, num_array, length, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_sort_array (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean simple_arr_comp_client_send_no_op (SimpleArrCompIf * iface, const GByteArray * num_array, const gint32 length, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "no_op", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "no_op_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "num_array", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) num_array)->data, ((GByteArray *) num_array)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "length", T_I32, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, length, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_recv_no_op (SimpleArrCompIf * iface, GByteArray ** _return, GError ** error)
{

  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SIMPLE_ARR_COMP_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "no_op", 5) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected no_op", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean simple_arr_comp_client_no_op (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, GError ** error)
{
  if (!simple_arr_comp_client_send_no_op (iface, num_array, length, error))
    return FALSE;
  if (!simple_arr_comp_client_recv_no_op (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
simple_arr_comp_if_interface_init (SimpleArrCompIfInterface *iface)
{
  iface->increment_array = simple_arr_comp_client_increment_array;
  iface->add_arrays = simple_arr_comp_client_add_arrays;
  iface->mat_multiply = simple_arr_comp_client_mat_multiply;
  iface->word_count = simple_arr_comp_client_word_count;
  iface->sort_array = simple_arr_comp_client_sort_array;
  iface->no_op = simple_arr_comp_client_no_op;
}

static void
simple_arr_comp_client_init (SimpleArrCompClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
simple_arr_comp_client_class_init (SimpleArrCompClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = simple_arr_comp_client_set_property;
  gobject_class->get_property = simple_arr_comp_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SIMPLE_ARR_COMP_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SIMPLE_ARR_COMP_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
simple_arr_comp_handler_simple_arr_comp_if_interface_init (SimpleArrCompIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (SimpleArrCompHandler, 
                         simple_arr_comp_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_SIMPLE_ARR_COMP_IF,
                                                simple_arr_comp_handler_simple_arr_comp_if_interface_init));

gboolean simple_arr_comp_handler_increment_array (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * arr, const gint8 value, const gint32 length, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->increment_array (iface, _return, arr, value, length, ouch, error);
}

gboolean simple_arr_comp_handler_add_arrays (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * array1, const GByteArray * array2, const gint32 length, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->add_arrays (iface, _return, array1, array2, length, ouch, error);
}

gboolean simple_arr_comp_handler_mat_multiply (SimpleArrCompIf * iface, const GByteArray * array, const GByteArray * matrix, const gint32 length, const tuple * dimension, const GByteArray * result_ptr, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->mat_multiply (iface, array, matrix, length, dimension, result_ptr, ouch, error);
}

gboolean simple_arr_comp_handler_word_count (SimpleArrCompIf * iface, gint32* _return, const GByteArray * story, const gint32 length, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->word_count (iface, _return, story, length, ouch, error);
}

gboolean simple_arr_comp_handler_sort_array (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, CallException ** ouch, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->sort_array (iface, _return, num_array, length, ouch, error);
}

gboolean simple_arr_comp_handler_no_op (SimpleArrCompIf * iface, GByteArray ** _return, const GByteArray * num_array, const gint32 length, GError ** error)
{
  g_return_if_fail (IS_SIMPLE_ARR_COMP_HANDLER (iface));

  SIMPLE_ARR_COMP_HANDLER_GET_CLASS (iface)->no_op (iface, _return, num_array, length, error);
}

static void
simple_arr_comp_handler_simple_arr_comp_if_interface_init (SimpleArrCompIfInterface *iface)
{
  iface->increment_array = simple_arr_comp_handler_increment_array;
  iface->add_arrays = simple_arr_comp_handler_add_arrays;
  iface->mat_multiply = simple_arr_comp_handler_mat_multiply;
  iface->word_count = simple_arr_comp_handler_word_count;
  iface->sort_array = simple_arr_comp_handler_sort_array;
  iface->no_op = simple_arr_comp_handler_no_op;
}

static void
simple_arr_comp_handler_init (SimpleArrCompHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
simple_arr_comp_handler_class_init (SimpleArrCompHandlerClass *cls)
{
  cls->increment_array = NULL;
  cls->add_arrays = NULL;
  cls->mat_multiply = NULL;
  cls->word_count = NULL;
  cls->sort_array = NULL;
  cls->no_op = NULL;
}

enum _SimpleArrCompProcessorProperties
{
  PROP_SIMPLE_ARR_COMP_PROCESSOR_0,
  PROP_SIMPLE_ARR_COMP_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (SimpleArrCompProcessor,
               simple_arr_comp_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR);

typedef gboolean (* SimpleArrCompProcessorProcessFunction) (SimpleArrCompProcessor *, 
                                                            gint32,
                                                            ThriftProtocol *,
                                                            ThriftProtocol *,
                                                            GError **);

static gboolean
simple_arr_comp_processor_process_increment_array (SimpleArrCompProcessor *self,
                                                   gint32 sequence_id,
                                                   ThriftProtocol *input_protocol,
                                                   ThriftProtocol *output_protocol,
                                                   GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompIncrementArrayArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_INCREMENT_ARRAY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * arr;
    gint value;
    gint length;
    CallException * ouch = NULL;
    GByteArray * return_value;
    SimpleArrCompIncrementArrayResult * result_struct;

    g_object_get (args,
                  "arr", &arr,
                  "value", &value,
                  "length", &length,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_INCREMENT_ARRAY_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (simple_arr_comp_handler_increment_array (SIMPLE_ARR_COMP_IF (self->handler),
                                                 &return_value,
                                                 arr,
                                                 value,
                                                 length,
                                                 &ouch,
                                                 error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "increment_array",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "increment_array",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("SimpleArrComp.increment_array implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "increment_array",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (arr != NULL)
      g_byte_array_unref (arr);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_process_add_arrays (SimpleArrCompProcessor *self,
                                              gint32 sequence_id,
                                              ThriftProtocol *input_protocol,
                                              ThriftProtocol *output_protocol,
                                              GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompAddArraysArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_ADD_ARRAYS_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * array1;
    GByteArray * array2;
    gint length;
    CallException * ouch = NULL;
    GByteArray * return_value;
    SimpleArrCompAddArraysResult * result_struct;

    g_object_get (args,
                  "array1", &array1,
                  "array2", &array2,
                  "length", &length,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_ADD_ARRAYS_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (simple_arr_comp_handler_add_arrays (SIMPLE_ARR_COMP_IF (self->handler),
                                            &return_value,
                                            array1,
                                            array2,
                                            length,
                                            &ouch,
                                            error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "add_arrays",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "add_arrays",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("SimpleArrComp.add_arrays implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "add_arrays",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (array1 != NULL)
      g_byte_array_unref (array1);
    if (array2 != NULL)
      g_byte_array_unref (array2);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_process_mat_multiply (SimpleArrCompProcessor *self,
                                                gint32 sequence_id,
                                                ThriftProtocol *input_protocol,
                                                ThriftProtocol *output_protocol,
                                                GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompMatMultiplyArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_MAT_MULTIPLY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * array;
    GByteArray * matrix;
    gint length;
    tuple * dimension;
    GByteArray * result_ptr;
    CallException * ouch = NULL;
    SimpleArrCompMatMultiplyResult * result_struct;

    g_object_get (args,
                  "array", &array,
                  "matrix", &matrix,
                  "length", &length,
                  "dimension", &dimension,
                  "result_ptr", &result_ptr,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_MAT_MULTIPLY_RESULT, NULL);

    if (simple_arr_comp_handler_mat_multiply (SIMPLE_ARR_COMP_IF (self->handler),
                                              array,
                                              matrix,
                                              length,
                                              dimension,
                                              result_ptr,
                                              &ouch,
                                              error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "mat_multiply",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "mat_multiply",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("SimpleArrComp.mat_multiply implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "mat_multiply",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (array != NULL)
      g_byte_array_unref (array);
    if (matrix != NULL)
      g_byte_array_unref (matrix);
    if (dimension != NULL)
      g_object_unref (dimension);
    if (result_ptr != NULL)
      g_byte_array_unref (result_ptr);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_process_word_count (SimpleArrCompProcessor *self,
                                              gint32 sequence_id,
                                              ThriftProtocol *input_protocol,
                                              ThriftProtocol *output_protocol,
                                              GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompWordCountArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_WORD_COUNT_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * story;
    gint length;
    CallException * ouch = NULL;
    gint return_value;
    SimpleArrCompWordCountResult * result_struct;

    g_object_get (args,
                  "story", &story,
                  "length", &length,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_WORD_COUNT_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (simple_arr_comp_handler_word_count (SIMPLE_ARR_COMP_IF (self->handler),
                                            (gint32 *)&return_value,
                                            story,
                                            length,
                                            &ouch,
                                            error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "word_count",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "word_count",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("SimpleArrComp.word_count implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "word_count",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (story != NULL)
      g_byte_array_unref (story);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_process_sort_array (SimpleArrCompProcessor *self,
                                              gint32 sequence_id,
                                              ThriftProtocol *input_protocol,
                                              ThriftProtocol *output_protocol,
                                              GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompSortArrayArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_SORT_ARRAY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * num_array;
    gint length;
    CallException * ouch = NULL;
    GByteArray * return_value;
    SimpleArrCompSortArrayResult * result_struct;

    g_object_get (args,
                  "num_array", &num_array,
                  "length", &length,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_SORT_ARRAY_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (simple_arr_comp_handler_sort_array (SIMPLE_ARR_COMP_IF (self->handler),
                                            &return_value,
                                            num_array,
                                            length,
                                            &ouch,
                                            error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "sort_array",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "sort_array",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("SimpleArrComp.sort_array implementation returned FALSE "
                     "but did not set an error");

        ThriftApplicationException *xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "sort_array",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (num_array != NULL)
      g_byte_array_unref (num_array);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_process_no_op (SimpleArrCompProcessor *self,
                                         gint32 sequence_id,
                                         ThriftProtocol *input_protocol,
                                         ThriftProtocol *output_protocol,
                                         GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  SimpleArrCompNoOpArgs * args =
    g_object_new (TYPE_SIMPLE_ARR_COMP_NO_OP_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * num_array;
    gint length;
    GByteArray * return_value;
    SimpleArrCompNoOpResult * result_struct;

    g_object_get (args,
                  "num_array", &num_array,
                  "length", &length,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_SIMPLE_ARR_COMP_NO_OP_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (simple_arr_comp_handler_no_op (SIMPLE_ARR_COMP_IF (self->handler),
                                       &return_value,
                                       num_array,
                                       length,
                                       error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "no_op",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("SimpleArrComp.no_op implementation returned FALSE "
                   "but did not set an error");

      ThriftApplicationException *xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "no_op",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (num_array != NULL)
      g_byte_array_unref (num_array);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
simple_arr_comp_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                         ThriftProtocol *input_protocol,
                                         ThriftProtocol *output_protocol,
                                         gchar *method_name,
                                         gint32 sequence_id,
                                         GError **error)
{
  SimpleArrCompProcessorProcessFunction process_function; 
  gboolean dispatch_result = FALSE;

  SimpleArrCompProcessor *self = SIMPLE_ARR_COMP_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (SIMPLE_ARR_COMP_PROCESSOR_GET_CLASS (self));

  process_function = g_hash_table_lookup (self->process_map, method_name);
  if (process_function != NULL)
  {
    dispatch_result = (*process_function) (self,
                                           sequence_id,
                                           input_protocol,
                                           output_protocol,
                                           error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
simple_arr_comp_processor_set_property (GObject *object,
                                        guint property_id,
                                        const GValue *value,
                                        GParamSpec *pspec)
{
  SimpleArrCompProcessor *self = SIMPLE_ARR_COMP_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_SIMPLE_ARR_COMP_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
simple_arr_comp_processor_get_property (GObject *object,
                                        guint property_id,
                                        GValue *value,
                                        GParamSpec *pspec)
{
  SimpleArrCompProcessor *self = SIMPLE_ARR_COMP_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_SIMPLE_ARR_COMP_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
simple_arr_comp_processor_dispose (GObject *gobject)
{
  SimpleArrCompProcessor *self = SIMPLE_ARR_COMP_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (simple_arr_comp_processor_parent_class)->dispose (gobject);
}

static void
simple_arr_comp_processor_finalize (GObject *gobject)
{
  SimpleArrCompProcessor *self = SIMPLE_ARR_COMP_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (simple_arr_comp_processor_parent_class)->finalize (gobject);
}

static void
simple_arr_comp_processor_init (SimpleArrCompProcessor *self)
{
  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  g_hash_table_insert (self->process_map,
                       "increment_array", 
                       simple_arr_comp_processor_process_increment_array);
  g_hash_table_insert (self->process_map,
                       "add_arrays", 
                       simple_arr_comp_processor_process_add_arrays);
  g_hash_table_insert (self->process_map,
                       "mat_multiply", 
                       simple_arr_comp_processor_process_mat_multiply);
  g_hash_table_insert (self->process_map,
                       "word_count", 
                       simple_arr_comp_processor_process_word_count);
  g_hash_table_insert (self->process_map,
                       "sort_array", 
                       simple_arr_comp_processor_process_sort_array);
  g_hash_table_insert (self->process_map,
                       "no_op", 
                       simple_arr_comp_processor_process_no_op);
}

static void
simple_arr_comp_processor_class_init (SimpleArrCompProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = simple_arr_comp_processor_dispose;
  gobject_class->finalize = simple_arr_comp_processor_finalize;
  gobject_class->set_property = simple_arr_comp_processor_set_property;
  gobject_class->get_property = simple_arr_comp_processor_get_property;

  dispatch_processor_class->dispatch_call = simple_arr_comp_processor_dispatch_call;
  cls->dispatch_call = simple_arr_comp_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_SIMPLE_ARR_COMP_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SIMPLE_ARR_COMP_PROCESSOR_HANDLER,
                                   param_spec);
}
